version: '2'
services:
    ng2-app:
        image: ng2
        external_links:
            - ng2-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ng2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ng2-mysql:
        extends:
            file: mysql.yml
            service: ng2-mysql
